// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_gen

var TableNames = struct {
	Affiliation            string
	Bookmarks              string
	Comments               string
	Communities            string
	CommunitiesRestaurants string
	InviteTokens           string
	Restaurants            string
	SchemaMigrations       string
	Users                  string
}{
	Affiliation:            "affiliation",
	Bookmarks:              "bookmarks",
	Comments:               "comments",
	Communities:            "communities",
	CommunitiesRestaurants: "communities_restaurants",
	InviteTokens:           "invite_tokens",
	Restaurants:            "restaurants",
	SchemaMigrations:       "schema_migrations",
	Users:                  "users",
}
